#!/usr/bin/env python3
"""Export db/philosophy.db into site/graph.js (the payload index.html loads).

Run: python3 scripts/seed.py && python3 scripts/build.py
"""
import json, os, sqlite3

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
con = sqlite3.connect(os.path.join(ROOT, 'db', 'philosophy.db'))
con.row_factory = sqlite3.Row

nodes, out = [], {}
for r in con.execute('SELECT * FROM person ORDER BY born'):
    nodes.append({'id': r['id'], 'k': 'p', 'label': r['name'], 'born': r['born'],
                  'died': r['died'], 'region': r['region'], 'sep': r['sep'],
                  'blurb': r['blurb']})
for r in con.execute('SELECT * FROM school ORDER BY span_from'):
    nodes.append({'id': r['id'], 'k': 'm', 'label': r['name'], 'born': r['span_from'],
                  'died': r['span_to'], 'sep': r['sep'], 'blurb': r['blurb']})
for r in con.execute('SELECT * FROM work ORDER BY year'):
    nodes.append({'id': r['id'], 'k': 'w', 'label': r['title'], 'born': r['year'],
                  'by': r['by'], 'blurb': r['blurb']})
for r in con.execute('SELECT * FROM quote'):
    nodes.append({'id': r['id'], 'k': 'q', 'label': r['text'], 'by': r['by'],
                  'work': r['work'], 'ref': r['ref'], 'flag': r['flag']})

edges = [[r['a'], r['b'], r['type']] for r in con.execute('SELECT * FROM edge')]
etypes = {r['type']: {'d': r['domain'], 'r': r['range'], 'f': r['label_fwd'],
                      'b': r['label_rev'], 'dir': r['directed'], 's': r['style']}
          for r in con.execute('SELECT * FROM edge_type')}

payload = {'nodes': nodes, 'edges': edges, 'types': etypes}
os.makedirs(os.path.join(ROOT, 'site'), exist_ok=True)
path = os.path.join(ROOT, 'site', 'graph.js')
with open(path, 'w') as f:
    f.write('/* GENERATED by scripts/build.py from db/philosophy.db - do not edit. */\n')
    f.write('window.GRAPH = ')
    json.dump(payload, f, ensure_ascii=False, separators=(',', ':'))
    f.write(';\n')
print(f'site/graph.js  {len(nodes)} nodes  {len(edges)} edges  {os.path.getsize(path)//1024} KB')
